title: Victor Bertalan's Page
profile_img: assets/img/profile.webp
icon_img: assets/img/icon.webp

name: "Victor Bertalan"
job: "PhD Candidate at Polytechnique Montréal"

phone_number: 438-938-6943
address: Montréal, Canada
email: vbertalan@gmail.com
linkedin_username: https://www.linkedin.com/in/vbertalan/
github_username: https://github.com/vbertalan/
instagram_username: https://www.instagram.com/vbertalan/
twitter_username: https://twitter.com/vbertalan/
facebook_username: https://www.facebook.com/vbertalan/
youtube_username: https://www.youtube.com/channel/UC_GsAwRQcjfyk8F7uK_eyNg/
blog_url: https://vbertalan.github.io/

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag