title: Victor Bertalan's Page
profile_img: assets/img/profile.webp
icon_img: assets/img/icon.webp

name: "Victor Bertalan"
job: "PhD Candidate at Polytechnique Montréal"

phone_number: 438-938-6943
address: Montréal, Canada
email: vbertalan@gmail.com
linkedin_username: vbertalan
github_username: vbertalan
instagram_username: vbertalan
twitter_username: vbertalan
facebook_username: vbertalan
youtube_username: _GsAwRQcjfyk8F7uK_eyNg
blog_url: vbertalan.github.io

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag